language: node_js

notifications:
  email:
    on_success: never

jobs:
  include:
    - stage: "PHP"
      name: "PHPStan on PS nightly and unit tests"
      language: php
      php: 7.2
      script:
        - composer install
        # PHP syntax check
        - bash -c '! (find . -name "*.php" ! -path "./vendor/*" -print0 | xargs -0 -n1 -P4 php -l | grep "Parse error")'
        # PHP cs fixer
        # - composer run lint
        # PHP Unit
        # - composer run test
        # PHP Stan
        - docker run -tid --rm -v ps-volume:/var/www/html --name temp-ps prestashop/prestashop:nightly
        # - docker exec -ti temp-ps rm -rf /var/www/html/modules/gsitemap
        # - docker run --rm --volumes-from temp-ps -v $PWD:/var/www/html/modules/gsitemap -e _PS_ROOT_DIR_=/var/www/html quetzacoalt/phpstan analyse --configuration=/var/www/html/modules/gsitemap/tests/php/phpstan/phpstan.neon
    - stage: "PHP"
      name: "PHPStan on PS 1.7.5.2"
      language: php
      php: 7.2
      script:
        - composer install
        - docker run -tid --rm -v ps-volume:/var/www/html --name temp-ps prestashop/prestashop:1.7.5.1
        # - docker exec -ti temp-ps rm -rf /var/www/html/modules/gsitemap
        # - docker run --rm --volumes-from temp-ps -v $PWD:/var/www/html/modules/gsitemap -e _PS_ROOT_DIR_=/var/www/html quetzacoalt/phpstan analyse --configuration=/var/www/html/modules/gsitemap/tests/php/phpstan/phpstan.neon
    - stage: "PHP"
      name: "PHPStan on PS 1.7.4.4"
      language: php
      php: 7.2
      script:
        - composer install
        - docker run -tid --rm -v ps-volume:/var/www/html --name temp-ps prestashop/prestashop:1.7.4.4
        # - docker exec -ti temp-ps rm -rf /var/www/html/modules/gsitemap
        # - docker run --rm --volumes-from temp-ps -v $PWD:/var/www/html/modules/gsitemap -e _PS_ROOT_DIR_=/var/www/html quetzacoalt/phpstan analyse --configuration=/var/www/html/modules/gsitemap/tests/php/phpstan/phpstan.neon
    - stage: "PHP"
      name: "PHPStan on PS 1.7.3.4"
      language: php
      php: 7.2
      script:
        - composer install
        - docker run -tid --rm -v ps-volume:/var/www/html --name temp-ps prestashop/prestashop:1.7.3.4
        # - docker exec -ti temp-ps rm -rf /var/www/html/modules/gsitemap
        # - docker run --rm --volumes-from temp-ps -v $PWD:/var/www/html/modules/gsitemap -e _PS_ROOT_DIR_=/var/www/html quetzacoalt/phpstan analyse --configuration=/var/www/html/modules/gsitemap/tests/php/phpstan/phpstan.neon
    - stage: "PHP"
      name: "PHPStan on PS 1.7.2.5"
      language: php
      php: 7.2
      script:
        - composer install
        - docker run -tid --rm -v ps-volume:/var/www/html --name temp-ps prestashop/prestashop:1.7.2.5
        #- docker exec -ti temp-ps rm -rf /var/www/html/modules/gsitemap
        #- docker run --rm --volumes-from temp-ps -v $PWD:/var/www/html/modules/gsitemap -e _PS_ROOT_DIR_=/var/www/html quetzacoalt/phpstan analyse --configuration=/var/www/html/modules/gsitemap/tests/php/phpstan/phpstan.neon
    - stage: "PHP"
      name: "PHPStan on PS 1.7.1.2"
      language: php
      php: 7.2
      script:
        - composer install
        - docker run -tid --rm -v ps-volume:/var/www/html --name temp-ps prestashop/prestashop:1.7.1.2
        # - docker exec -ti temp-ps rm -rf /var/www/html/modules/gsitemap
        # - docker run --rm --volumes-from temp-ps -v $PWD:/var/www/html/modules/gsitemap -e _PS_ROOT_DIR_=/var/www/html quetzacoalt/phpstan analyse --configuration=/var/www/html/modules/gsitemap/tests/php/phpstan/phpstan.neon
